import Head from 'next/head';
import { withIronSessionSsr } from 'iron-session/next';
import { Layout } from 'antd';

import sessionOptions from '../lib/session';
import constants from '../lib/constants';
import LoginForm from '../components/login-form';
import Header from '../components/header';

export default function Login({ isLoggedIn }) {
  return (
    <Layout className="layout">
      <Head>
        <title>Nextjs Web - I Komang Sena</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout.Header>
        <Header isLoggedIn={isLoggedIn} />
      </Layout.Header>
      <Layout.Content style={{ padding: '0 50px', marginTop: 16 }}>
        <div className="site-layout-content">
          <LoginForm />
        </div>
      </Layout.Content>
      <Layout.Footer style={{ textAlign: 'center' }}>
        Copyright (c) 2022
        {' '}
        <a
          href="http://sena.omg.lol"
          target="_blank"
          rel="noreferrer"
        >
          I Komang Sena Aji Buwana
        </a>
      </Layout.Footer>
    </Layout>
  );
}

export const getServerSideProps = withIronSessionSsr(async ({ req }) => {
  if (req.session.user?.isLoggedIn) {
    return {
      redirect: {
        destination: `${constants.BASE_URL}/home`,
        permanent: false,
      },
    };
  }

  return {
    props: {
      isLoggedIn: false,
    },
  };
}, sessionOptions);
