import Head from 'next/head';
import { withIronSessionSsr } from 'iron-session/next';

import sessionOptions from '../lib/session';
import constants from '../lib/constants';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Nextjs Web - I Komang Sena</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <footer>
        <a
          href="http://sena.omg.lol"
          target="_blank"
          rel="noreferrer"
        >
          Copyright (c) 2022 I Komang Sena Aji Buwana
        </a>
      </footer>
    </div>
  );
}

export const getServerSideProps = withIronSessionSsr(async ({ req }) => {
  if (req.session.user) {
    return {
      redirect: {
        destination: `${constants.BASE_URL}/home`,
        permanent: false,
      },
    };
  }

  return {
    props: {},
  };
}, sessionOptions);
